apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - portfolio.yaml    # This includes your app config
  #- image-automation.yaml # This includes your new automation
