apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: portfolio-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/a-nasruddin/k8s-manifest.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portfolio-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./portfolio
  prune: true
  sourceRef:
    kind: GitRepository
    name: portfolio-repo
  targetNamespace: default
